apiVersion: v1
kind: Service
metadata:
  # Il nome del service deve essere prevedibile (es. onboarding-backend)
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    part-of: adhr-enterprise-suite
    env: {{ .Values.env | default "dev" }}
spec:
  # ClusterIP. È lo standard perché rende l'app raggiungibile solo dentro il cluster. 
  # Sarà poi l'Ingress ad aprirla al mondo esterno. 
  type: ClusterIP
  ports:
    - port: 80          # La porta "virtuale" del Service dentro il cluster
      targetPort: http  # Punta al nome della porta definita nel Deployment (o direttamente al numero)
      protocol: TCP
      name: http
  selector:
    # Fondamentale: deve matchare ESATTAMENTE le labels del template dei Pod nel Deployment
    app: {{ .Release.Name }}