services:
    welcome-frontend:
        # qui definiamo delle build arguments. le args servono solo durante la creazione
        # dell'immagine, cioè mentre docker esegue:
        # RUN pnpm turbo build --filter=@adhr/welcome-frontend i valori ${} sono presi
        # dal file .env ( default ) oppure dal file che dichiariamo con --env-file
        # docker compose --env-file apps/welcome-frontend/.env.production up ecc ...

        # Queste variabili vengono iniettate nel Dockerfile e affinchè Docker possa
        # utilizzarle devono esserci ARG_DATABASE_URL dentro DockerFile.
        # Una volta che l'immagine è creata, queste variabili "spariscono"
        # a meno che non vengano usate per compilare qualcosa di statico.

        build:
            context: .
            dockerfile: apps/welcome-frontend/Dockerfile
            args:
                NEXT_PUBLIC_NODE_ENV: ${NEXT_PUBLIC_NODE_ENV:-}

        # Sintassi per concatenare: [Variabile]-[Testo Fisso]
        # Se NODE_ENV=production -> welcome-frontend:production-latest
        # Se NODE_ENV è vuoto -> welcome-frontend:latest
        image: welcome-frontend:${NODE_ENV:+$NODE_ENV-}latest
        container_name: welcome-frontend
        ports:
            - '3000:3000'

        # Per fare in modo che il compoenente legga i dati al runtime li mettiamo qui
        environment:
            NODE_ENV: ${NODE_ENV}
            ENVIRONMENT: ${ENVIRONMENT}
            AUTH_KEYCLOAK_ID: ${AUTH_KEYCLOAK_ID}
            AUTH_KEYCLOAK_SECRET: ${AUTH_KEYCLOAK_SECRET}
            AUTH_KEYCLOAK_ISSUER: ${AUTH_KEYCLOAK_ISSUER}
            AUTH_SECRET: ${AUTH_SECRET}
            AUTH_URL: ${AUTH_URL}
            AI_BACKEND_URL: "http://ai-backend:3002"

        restart: unless-stopped

    welcome-backend:
        build:
            context: .
            dockerfile: apps/welcome-backend/Dockerfile
            args:
                NODE_ENV: ${NODE_ENV}

        image: welcome-backend:${NODE_ENV:+$NODE_ENV-}latest
        container_name: welcome-backend
        ports:
            - '3001:3001'

        environment:
            HOSTNAME: 0.0.0.0
            PORT: 3001
            NODE_ENV: ${NODE_ENV}
            DATABASE_URL: ${DATABASE_URL}

        restart: unless-stopped

    ai-backend:
        build:
            context: .
            dockerfile: apps/ai-backend/Dockerfile
            args:
                NODE_ENV: ${NODE_ENV}

        image: ai-backend:${NODE_ENV:+$NODE_ENV-}latest
        container_name: ai-backend
        ports:
            - '3002:3002'

        environment:
            # Sovrascriviamo l'URL per farlo parlare con il port-forward sul MIO PC
            # http://host.docker.internal:11434/v1 => 172.18.0.1 dove c'è il MIO PC
            # per questo motivo se metto: 
            # kubectl port-forward --address 0.0.0.0 svc/ai-service 11434:80 -n development
            # dico al forwarder di mettersi in ascolto su tutte le interfacce di rete alla porta 
            # 11434 e spedirle a svx/ai-service porta 80.

            HOST: '0.0.0.0'
            AI_BASE_URL: "http://host.docker.internal:11434/v1"
            AI_MODEL_NAME: ${AI_MODEL_NAME}            
            AI_EMBEDDING_MODEL_NAME: ${AI_EMBEDDING_MODEL_NAME}
            PORT: "3002"
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            NODE_ENV: ${NODE_ENV}
            
            
        extra_hosts:
            - 'host.docker.internal:host-gateway'

        restart: unless-stopped
