image:
    repository: adhresregistry.azurecr.io/welcome-frontend
    tag: 'temp' # Verrà sovrascritto da --set nella GitHub Action
    pullPolicy: Always

service:
    port: 3000

config:
    aiBackendUrl: 'http://ai-backend'

ingress:
    enabled: true
    host: 'welcome.4.232.3.98.nip.io'
    annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
ambiente: azure
replicaCount: 1

resources:
    requests:
        cpu: '20m'
        memory: '128Mi'
    limits:
        cpu: '100m'
        memory: '256Mi'
