image:
  repository: adhresregistry.azurecr.io/welcome-frontend
  tag: "temp" # Verrà sovrascritto da --set nella GitHub Action
  pullPolicy: Always

service:
  port: 3000

config:
  backendUrl: "http://welcome.backend" 

ingress:
  enabled: true
  host: "frontend.4.232.3.98.nip.io"

ambiente: azure
replicaCount: 1