apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: localai-models-pvc
    namespace: development
    labels:
        Project: AdhrEnterpriseSuite
        Owner: SistemiInformativi
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: default
    resources:
        requests:
            storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: localai
    namespace: development
    labels:
        Project: AdhrEnterpriseSuite
        Owner: SistemiInformativi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: localai
    template:
        metadata:
            labels:
                app: localai
                Project: AdhrEnterpriseSuite
        spec:
            containers:
                - name: localai
                  # Cambio immagine: 'latest-cpu' è molto più leggera della 'aio'
                  image: localai/localai:latest-cpu
                  resources:
                      requests:
                          cpu: '500m'
                          memory: '2000Mi'
                      limits:
                          cpu: '1000m'
                          memory: '2600Mi' # Leggero aumento per dare un filo di respiro in più
                  env:
                      - name: MODELS_PATH
                        value: '/models'
                      - name: THREADS
                        value: '1' # 1 Thread = 1 CPU. Evita "ingorghi" di calcolo.
                      - name: CONTEXT_SIZE
                        value: '512' # CRUCIALE: dimezza l'uso della RAM per i messaggi.
                      - name: F16_KV
                        value: 'false' # Risparmia ulteriore memoria.
                      - name: GALLERIES
                        value: '[]' # Disabilita download automatici all'avvio.
                  volumeMounts:
                      - name: models
                        mountPath: /models
            volumes:
                - name: models
                  persistentVolumeClaim:
                      claimName: localai-models-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: localai-service
    namespace: development
spec:
    selector:
        app: localai
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
